def get_event_details_from_user():
    """
    Get event details from user input
    """
    print("\n" + "="*50)
    print("EVENT DETAILS INPUT")
    print("="*50)
    
    date = input("Enter event date (YYYY-MM-DD): ")
    time = input("Enter event time (HH:MM): ")
    activity = input("Enter activity type (e.g., road_accident, theft, vandalism): ")
    
    print("\nLocation Details:")
    street = input("Enter street name: ")
    city = input("Enter city: ")
    state = input("Enter state: ")
    
    event = {
        "date": date,
        "time": time,
        "activity": activity,
        "location": {
            "street": street,
            "city": city,
            "state": state
        }
    }
    
    return event


def load_damage_from_report(report_path="damage_report.json"):
    """
    Load damage data from the JSON report generated by overlay.py
    """
    import json
    import os
    
    # Default damage data
    default_damage = {
        "type": "partial",
        "damaged_parts": [
            {
                "part_name": "front_bumper",
                "severity": 0.4
            },
            {
                "part_name": "headlamp_left",
                "severity": 0.7
            }
        ]
    }
    
    # Try to load from damage_report.json if it exists
    if os.path.exists(report_path):
        try:
            with open(report_path, 'r') as f:
                report = json.load(f)
                return report.get("damage", default_damage)
        except Exception as e:
            print(f"Warning: Could not load damage report from {report_path}: {e}")
            print("Using default damage data...")
            return default_damage
    else:
        print(f"Note: {report_path} not found. Using default damage data...")
        return default_damage


def create_claim_json(event_data=None):
    """
    Create claim JSON with user-provided event data
    If event_data is None, uses default values
    Damage data is loaded from damage_report.json if available
    """

    # Use provided event data or default values
    if event_data is None:
        event_data = {
            "date": "2025-01-15",
            "time": "18:45",
            "activity": "road_accident",
            "location": {
                "street": "Baner Road",
                "city": "Pune",
                "state": "Maharashtra"
            }
        }

    # Load damage data from overlay.py output
    damage_data = load_damage_from_report()

    claim = {
        "event": event_data,

        "driver": {
            "name": "Amit Kulkarni",
            "age": 34,
            "gender": "male",
            "licensed": True,
            "experience_years": 12,
            "under_influence": False
        },

        # 🔑 IMPORTANT CHANGE IS HERE
        "vehicle": {
            "type": "private",      # matches policy eligibility
            "category": "car",      # matches vehicle dataset type
            "usage": "private"
        },

        "damage": damage_data,

        "policy": {
            "active": True
        }
    }

    return claim
